# Generated by Django 5.1.6 on 2025-05-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='api_id',
            field=models.CharField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
