# Generated by Django 5.1.6 on 2025-05-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_remove_exercise_saver_exercise_body_part_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedexercise',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='savedexercise',
            constraint=models.UniqueConstraint(fields=('user', 'exercise'), name='unique_user_exercise'),
        ),
    ]
