# Generated by Django 5.1.6 on 2025-05-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_remove_savedexercise_unique_user_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedexercise',
            name='exercise_id',
            field=models.CharField(max_length=100),
        ),
    ]
