# Generated by Django 5.1.6 on 2025-05-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_alter_savedexercise_exercise_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
